SELECT
	SHP.SHP_SHIPMENT_ID,
	LG.SHP_LG_FACILITY_ORIGIN_ID AS ORIGEM,
	ITEMS[SAFE_OFFSET(0)].SHP_ITEM_DESC AS SHP_ITEM_DESC,
	SHP.SHP_ORDER_COST AS VALOR_REAL,
	LG.SHP_LG_STATUS,
	LG.SHP_LG_SUB_STATUS,
	LG.SHP_LG_PROMISE_DT_TO,
	LG.SHP_LG_PROMISE_DT_FROM,
	LG.SHP_LG_LAST_UPDATED AS shp_lg_last_updated
FROM
	`meli-bi-data.WHOWNER.BT_SHP_SHIPMENTS` AS SHP
	LEFT JOIN `meli-bi-data.WHOWNER.BT_SHP_LG_SHIPMENTS` AS LG ON SHP.SHP_SHIPMENT_ID = LG.SHP_SHIPMENT_ID
WHERE
	SHP.SHP_SHIPMENT_ID IN ()
ORDER BY
	LG.SHP_LG_LAST_UPDATED DESC
