SELECT
    t.SHP_SHIPMENT_ID,
    ite.SHP_ITEM_DESC,
    t.SHP_ORDER_COST AS VALOR_REAL,
    lg.SHP_LG_STATUS,
    lg.SHP_LG_SUB_STATUS,
    lg.SHP_LG_PROMISE_DT_TO,
    lg.SHP_LG_PROMISE_DT_FROM,
    lg.SHP_LG_LAST_UPDATED
FROM
    `meli-bi-data`.`WHOWNER`.`BT_SHP_SHIPMENTS` AS t,
    UNNEST (t.ITEMS) AS ite
    INNER JOIN `meli-bi-data`.`WHOWNER`.`BT_SHP_LG_SHIPMENTS` AS lg ON t.SHP_SHIPMENT_ID = lg.SHP_SHIPMENT_ID
WHERE
    t.SHP_SHIPMENT_ID IN (45662888229)
ORDER BY
    lg.SHP_LG_LAST_UPDATED DESC;