SELECT
    r.SHP_FACILITY_ID AS facility_id,
    r.RTG_ROUTE_ORIGIN.SHP_FACILITY_TYPE AS Tipo_de_operacao,
    r.RTG_ROUTE_ORIGIN.SHP_FACILITY_ID AS Codigo,
    r.SHP_CYCLE.name AS cycle,
    r.SHP_CYCLE.contingency AS contingency,
    r.RTG_ROUTE_ID AS route_id,
    r.RTG_ROUTE_UUID AS route_uuid,
    r.RTG_ROUTE_NAME AS route_name,
    r.RTG_ROUTE_SUMMARIES.TRAVEL_TIME AS travel_time,
    TIME(TIMESTAMP_SECONDS(CAST(r.RTG_ROUTE_SUMMARIES.TRAVEL_TIME AS INT64) * 60)) AS MAX_TRAVEL_TIME,
    r.RTG_ROUTE_SUMMARIES.TRAVEL_DISTANCE AS travel_distance,
    r.RTG_ROUTE_SUMMARIES.VOLUME_OCCUPANCY AS volumen_occupancy,
    r.SHP_LG_VEHICLE_TYPE_ID AS vehicle_type_id,
    vt.SHP_LG_VEHICLE_TYPE AS vehicle,
    r.RTG_ROUTE_SUMMARIES.UNITS AS spr,
    s.RTG_STOP_SEQUENCE AS stop_sequence,
    sa.rtg_action_sequence AS action_sequence,
    sa.RTG_ACTION_OPERATION_TYPE AS action_type,
    sau.RTG_UNIT_EXTERNAL_ID AS unit_id,
    u.RTG_UNIT_ADDRESS_INFO.CITY AS city,
    u.RTG_UNIT_ADDRESS_INFO.STATE AS state,
    u.RTG_UNIT_ADDRESS_INFO.ZIPCODE AS zip_code,
    sau.RTG_UNIT_EXTERNAL_TYPE AS unit_type,
    IUN_UNIT_ID
FROM
    `meli-bi-data.WHOWNER.BT_SHP_LG_RTG_ROUTE` r
LEFT JOIN
    `meli-bi-data.WHOWNER.LK_SHP_LG_VEHICLES_TYPES` vt
    ON vt.SHP_LG_VEHICLE_TYPE_ID = r.SHP_LG_VEHICLE_TYPE_ID
INNER JOIN
    `meli-bi-data.WHOWNER.BT_SHP_LG_RTG_STOP` s
    ON s.RTG_ROUTE_UUID = r.RTG_ROUTE_UUID
    AND s.RTG_STOP_LAST_UPDATED_DTTM >= DATETIME_SUB(CAST(CURRENT_DATE() AS DATETIME), INTERVAL 3 DAY)
INNER JOIN
    `meli-bi-data.WHOWNER.BT_SHP_LG_RTG_STOP_ACTION` sa
    ON sa.RTG_STOP_UUID = s.RTG_STOP_UUID
    AND sa.RTG_ACTION_LAST_UPDATED_DTTM >= DATETIME_SUB(CAST(CURRENT_DATE() AS DATETIME), INTERVAL 3 DAY)
INNER JOIN
    `meli-bi-data.WHOWNER.BT_SHP_LG_RTG_STOP_ACTION_UNIT` sau
    ON sau.RTG_ACTION_UUID = sa.RTG_ACTION_UUID
    AND sau.RTG_ACTION_LAST_UPDATED_DTTM >= DATETIME_SUB(CAST(CURRENT_DATE() AS DATETIME), INTERVAL 3 DAY)
INNER JOIN
    `meli-bi-data.WHOWNER.BT_SHP_LG_RTG_PLANIFICATION_UNIT` u
    ON u.RTG_UNIT_UUID = sau.RTG_UNIT_UUID
WHERE
    r.SIT_SITE_ID = 'MLB'
    AND r.SHP_FACILITY_ID = 'SMG2'
    AND r.RTG_ROUTE_ORIGIN.SHP_FACILITY_TYPE = 'nex'
    AND DATE(r.RTG_ROUTE_DEPARTURE_DTTM) = CURRENT_DATE()
    -- AND r.SHP_CYCLE.name = 'AM101'
    AND r.RTG_ROUTE_STATUS = 'planned'
ORDER BY
    route_name,
    cycle,
    contingency,
    stop_sequence,
    action_sequence;
