SELECT
	SHP.SHP_SHIPMENT_ID AS SHIPMENT_ID,
	LG.SHP_LG_FACILITY_ORIGIN_ID AS ORIGEM, -- Traz a sigla do Facility (Ex: XMG1, BRXSP1)
	CAST(SHP.SHP_DATE_CREATED_ID AS DATE) AS DATA,
	CAST(SHP.SHP_DATE_HANDLING_ID AS DATE) AS DATA2,
	SHP.SHP_RECEIVER_CITY_NAME AS DESTINO,
	SHP.SHP_ORDER_COST AS CUSTO_REAL,
	ITEMS[SAFE_OFFSET(0)].SHP_ITEM_DESC AS DESC_PRODUTO
FROM
	`meli-bi-data.WHOWNER.BT_SHP_SHIPMENTS` AS SHP
	LEFT JOIN `meli-bi-data.WHOWNER.BT_SHP_LG_SHIPMENTS` AS LG ON SHP.SHP_SHIPMENT_ID = LG.SHP_SHIPMENT_ID
WHERE
	SHP.SHP_SHIPMENT_ID IN ()
