SELECT DISTINCT
    A.SHP_SHIPMENT_ID AS ID,
    A.SHP_LG_FACILITY_ID AS SVC,
    CAST(A.shp_lg_route_init_date AS DATE) AS DATA_ROTA,
    A.SHP_LG_ROUTE_ID AS ID_ROTA,
    R.SHP_LG_CLUSTER_ID,
    A.SHP_LG_DRIVER_ID AS Cod_Motorista,
    LR.ROUTE.DRIVER.NAME AS NOME_MOTORISTA,
    A.SHP_LG_VEHICLE_PLATE_ID AS Placa,
    A.SHP_LG_VEHICLE_TYPE AS TIPO_VEICULO,
    A.shp_company_ID AS ID_TSP,
    B.shp_company_name AS TRANSPORTADORA,
    CAST(A.AUD_INS_DTTM AS TIME) AS hour,
    A.shp_lg_shipment_sub_status AS MOTIVO,
    COALESCE(LR.ROUTE.DESTINATION_FACILITY.FACILITY_ID, 'SVC') AS ID_DA_INSTALACAO_DESTINO
FROM
    `meli-bi-data.WHOWNER.BT_SHP_LG_SHIPMENTS_ROUTES` A
    LEFT JOIN `meli-bi-data.WHOWNER.LK_SHP_COMPANIES` B ON A.shp_company_ID = B.SHP_company_ID
    LEFT JOIN `meli-bi-data.WHOWNER.LK_SHP_LG_ROUTES` R ON A.SHP_LG_ROUTE_ID = R.SHP_LG_ROUTE_ID
    LEFT JOIN `meli-bi-data.WHOWNER.BT_SHP_MT_LOGISTICS_ROUTE` LR ON CAST(A.SHP_LG_ROUTE_ID AS STRING) = LR.ID
WHERE
    A.shp_lg_facility_id = 'SMG2'
    --AND CAST(A.shp_lg_route_init_date AS DATE) BETWEEN '2025-09-17' AND '2025-09-17'--período
    AND CAST(A.shp_lg_route_init_date AS DATE) = '2026-03-16' --data avulsa