SELECT
    A.SHP_SHIPMENT_ID AS ID_PACOTE,
    A.SHP_LG_CLAIMS_ID AS ID_REIVINDICACAO,
    A.SHP_LG_STATUS,
    A.SHP_LG_REASON_TYPE AS TIPO_REIVINDICACAO,
    A.SHP_LG_REASON_NAME,
    A.SHP_LG_SHIPMENT_STATUS,
    A.SHP_LG_SHIPMENT_SUBSTATUS,
    B.MESSAGE AS MENSAGEM,
    CLAIM_OPENED_DT AS DATA_ABERTURA
FROM `meli-bi-data.WHOWNER.LK_SHP_LG_CLAIMS` A
LEFT JOIN `meli-bi-data.WHOWNER.DM_SHP_LOGISTICS_CLAIMS` B
    ON A.SHP_LG_CLAIMS_ID = B.CLA_CLAIM_ID
WHERE A.SHP_SHIPMENT_ID IN (INSIRA_O_ID_DO_PACOTE_AQUI)
