SELECT
    R.SHP_LG_ROUTE_ID,
    R.SHP_LG_CLUSTER_ID
FROM
    `meli-bi-data.WHOWNER.LK_SHP_LG_ROUTES` R
    INNER JOIN `meli-bi-data.WHOWNER.LK_SHP_LG_ROUTE_STOP` RS ON RS.SHP_LG_ROUTE_ID = R.SHP_LG_ROUTE_ID
WHERE
    R.SHP_LG_ROUTE_ID = 352472856 -- INSIRA O ID DA SUA ROTA AQUI
LIMIT
    1;