WITH
	BASE AS (
		SELECT
			*
		FROM
			meli-bi-data.WHOWNER_FEED.SHIPPING_SORTING_HISTORY
		WHERE
			FACILITY_ID = 'SMG2' -- ALTERE AQUI PARA O SEU SVC
			AND CONTAINER_TYPE = 'bag'
			AND DATE(EVENT_DATE) = CURRENT_DATE() -- ALTERE A DATA SE NECESSÁRIO
			AND EXTERNAL_REFERENCE <> 0
	),
	SORTING AS (
		SELECT DISTINCT
			SHP_SHIPMENT_ID,
			SHP_LG_DATE_CREATED AS HORARIO_DE_INDUCAO
		FROM
			meli-bi-data.WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
		WHERE
			SHP_NODE_ID = 'SMG2' -- ALTERE AQUI PARA O SEU SVC
			AND UPPER(SHP_LG_SUB_STATUS) = 'SORTING'
			AND DATE(SHP_LG_DATE_CREATED) = CURRENT_DATE() -- ALTERE A DATA SE NECESSÁRIO
	),
	GUARDA AS (
		SELECT DISTINCT
			SHP_SHIPMENT_ID,
			SHP_LG_DATE_CREATED AS HORARIO_DE_GUARDA
		FROM
			meli-bi-data.WHOWNER.BT_SHP_LG_SHIPMENT_CHECKPOINTS
		WHERE
			SHP_NODE_ID = 'SMG2' -- ALTERE AQUI PARA O SEU SVC
			AND UPPER(SHP_LG_SUB_STATUS) = 'IN_CONTAINER'
			AND DATE(SHP_LG_DATE_CREATED) = CURRENT_DATE() -- ALTERE A DATA SE NECESSÁRIO
	)
SELECT
	b.*,
	-- Ajuste: somar 1 hora se houver valor
	IF(
		s.HORARIO_DE_INDUCAO IS NULL,
		NULL,
		TIMESTAMP_ADD(s.HORARIO_DE_INDUCAO, INTERVAL 1 HOUR)
	) AS HORARIO_DE_INDUCAO,
	IF(
		g.HORARIO_DE_GUARDA IS NULL,
		NULL,
		TIMESTAMP_ADD(g.HORARIO_DE_GUARDA, INTERVAL 1 HOUR)
	) AS HORARIO_DE_GUARDA
FROM
	BASE b
	LEFT JOIN SORTING s ON b.EXTERNAL_REFERENCE = s.SHP_SHIPMENT_ID
	LEFT JOIN GUARDA g ON b.EXTERNAL_REFERENCE = g.SHP_SHIPMENT_ID
ORDER BY
	EVENT_DATE DESC;
